### ISSUE TITLE
Dataset attributes should be added as normal attributes

### ISSUE THREAD

**Issue by wesleytodd** [marcelklehr/vdom-virtualize#11]
https://github.com/Matt-Esch/vdom/pull/14#issuecomment-60799003

As said in the above issue, it might be better to change [this section](https://github.com/marcelklehr/vdom-virtualize/blob/master/index.js#L95) to use attributes even though they are actually dataset values.  Any thoughts on this?

**Comment by marcelklehr** [comment]
I've finally been able to consider this and have reached a verdict: Accepted! ;)

**Comment by wesleytodd** [comment]
Ha, well cool!  Although I gave up with virtual-dom for the time being in our production app.  I am still interested in the project because it would be good to have lower level virtual dom components, rather than just being stuck with React :)
