### ISSUE TITLE
use without browserfy

### ISSUE THREAD

**Issue by episodeyang** [marcelklehr/vdom-virtualize#12]
Hey @marcelklehr ,

Thanks for this great work! Is it possible for me to use this without browserfy, with virtual-dom? 

I saw that there was a dist.js file in mercury : https://github.com/Raynos/mercury/blob/master/dist/mercury.js

but I am not sure if that contains this lib.

Thanks!
Ge

**Comment by marcelklehr** [comment]
Hey, I know this is late news, but I just created a standalone browserified bundle that exports to `window.vdomVirtualize`
