### ISSUE TITLE
Support for attributes?

### ISSUE THREAD

**Issue by episodeyang** [marcelklehr/vdom-virtualize#13]
Hi @marcelklehr ,

Does vdom-virtualize support attributes? For example, I have `alt` attribute in my dom that contains crucial information that I can't leave inside the element. 

I saw your comment in #1. Is this a problem with `virtual-dom` or it is something that we can change by patching up this virtualizer?

Thanks!
Ge

**Comment by marcelklehr** [comment]
Attributes are now supported!
