### ISSUE TITLE
Didn't you forget the type ?

### ISSUE THREAD

**Issue by cedvdb** [marcelklehr/vdom-virtualize#43]
I can't manage to use this with virtual-dom. If I pass a virtual node made through your library to virtual-dom createElement method, the return value is always null because the type of the object isn't VirtualNode.

Here is a quick sample trying to change a div into vdom:

```
let Rx = require("rxjs");
let virtualize = require('vdom-virtualize');
let h = require("virtual-dom/h")
let diff = require("virtual-dom/diff")
let createElement = require("virtual-dom/create-element")
let patch = require("virtual-dom/patch")



let d = document.getElementById('d');
let t = virtualize(d);
console.log(t); //VirtualNode {tagName: "DIV", properties: Object, children: Array[5], key: undefined, namespace: null…}
debugger
let rootNode = createElement(d)
console.log(rootNode); //root is null
```

**Comment by marcelklehr** [comment]
Actually, the code uses the [virtual-dom module](https://github.com/marcelklehr/vdom-virtualize/blob/master/index.js#L24) for [creating](https://github.com/marcelklehr/vdom-virtualize/blob/master/index.js#L59) VNodes. The problem might be a version mismatch, though. Could you check that?

**Comment by marcelklehr** [comment]
Just noticed: you're calling createElement on `d`, when you should be calling it on `t`. ;)
