### ISSUE TITLE
fromHTML adds nodes to the document, but doesn't delete them

### ISSUE THREAD

**Issue by jfsiii** [marcelklehr/vdom-virtualize#6]
See [this RequireBin](http://requirebin.com/?gist=eb96a5c2580e6154a1a6).

250+ nodes were created in ~10 seconds: 
![screen shot 2014-07-22 at 7 24 37 pm](https://cloud.githubusercontent.com/assets/57655/3667974/cde32c7e-1210-11e4-99a4-673ff8c53c03.png)

I believe this is because DOM nodes are [continually created but not reused or removed](https://github.com/marcelklehr/vdom-virtualize/blob/9e2da942c787cd9f9c1c745f3a74a08d8158d471/index.js#L37-L42).

Please let me know if you see something wrong with my test case.

**Comment by paulocheque** [comment]
I tried `window.virtualize.fromHTML('<h1>teste</h1')` and ir returns an `html` and `body` nodes. Is that necessary?

**Comment by marcelklehr** [comment]
parsing HTML *correctly* is hard, so I've removed fromHTML and recommend using https://github.com/TimBeyer/html-to-vdom instead -- If you want HTML parsing, use that. If you already have a DOM tree, virtualize will probably be more performant.

**Comment by paulocheque** [comment]
Thanks!
