### ISSUE TITLE
Server-side HTML parsing

### ISSUE THREAD

**Issue by gsf** [marcelklehr/vdom-virtualize#7]
As I mentioned at TimBeyer/html-to-vdom#1 I'm using vdom-virtualize in my rendering, and it's working splendidly. I would like to use the same render code on the server, however. 

I believe we could get most of the way there if we check for `window === undefined` and switch to [parse5](https://github.com/inikulin/parse5) for DOM tree creation in the fromHTML method. Unfortunately, there are several discrepancies between the browser and parse5 trees for which we would have to do further processing or pass a custom treeAdapter into parse5:

1. In the parse5 tree there's no nodeType property, but nodeName is either the tag name or "#text".
2. Text nodes have their text in "value", not "nodeValue".
3. Nodes in the default parse5 tree have childNodes but not children.
4. Rather than create properties on the node, parse5 leaves attributes as they are and sticks them in an "attrs" array.

I'm thinking a custom treeAdapter would make sense, though I'm not excited about mapping attributes to HTMLElement properties.

**Comment by marcelklehr** [comment]
So, I'm closing this now as I've decided this is outside the scope of this library. If you already have a DOM tree (as is usually the case in the browser) use virtualize, if you want to parse HTML use https://github.com/TimBeyer/html-to-vdom ;)
